### ISSUE TITLE
Modify file pom for first part of project's implementation

### ISSUE THREAD

**Issue by matteoghera** [LorenzoEscriva/ProgettoFinale#1]
Add the following plugins/dependecies:

1. change junit version to 4.12;
2. mockito
3. log4j (only messages to console)
4. jacoco for coveralls (exclude the test's classes)
5. coveralls
6. pitest (as properties)

**Comment by LorenzoEscriva** [comment]
Matte, 1,2,3 fatti. Jacoco e coveralls non ho capito cosa vuoi fare adesso. Pitest come proprietà non so come farla, illuminami. Ps. ho aperto il branch issue#1, una volta completata facciamo la pull request, non modificare direttamente il master! (ma dobbiamo scrivere in inglese per forza? cioè non è un problema eh, però è così necessario? )

**Comment by matteoghera** [comment]
Qui in inglese, su Whatsapp in italiano

**Comment by matteoghera** [comment]
View this tutorial (end of the document):
https://e-l.unifi.it/pluginfile.php/223104/mod_resource/content/1/mutation%20testing%20tutorial.pdf

**Comment by LorenzoEscriva** [comment]
PIT è usato come plugin in quel tutorial, devo metterlo così? ps. secondo me non ha senso, pit lo useremo noi ma non ha senso metterlo nel progetto. Pps. io scrivo in italiano, perchè già c'è da fare mille cose, meglio capirsi veloce e soprattutto in italiano scrivo più veloce.
