### ISSUE TITLE
Implement all method

### ISSUE THREAD

**Issue by matteoghera** [LorenzoEscriva/ProgettoFinale#23]
Implement the remainder method

**Comment by matteoghera** [comment]
You must implemented this remain method:
add( ) with this message for Session class: "adds the journal entry with id "+ id;
modify( ) with this message for Session class: "changes the journal entry  with id " + id
delete( ) with this message for Session class: "deletes the journal entry with id " +id
getAllRegistration( ) with this message for Session class: " takes all journal entry  between "+ date1.toString()+ " and " date2.toString()
You must use the Session class for log.

**Comment by LorenzoEscriva** [comment]
Look at the new branch and answer me on whatsapp.
