### ISSUE TITLE
Add AccountantAppIT test class

### ISSUE THREAD

**Issue by matteoghera** [LorenzoEscriva/ProgettoFinale#28]
Add AccountantAppIT test class at the package com.tap.project.escrivaghera.AccountantApp.it

**Comment by LorenzoEscriva** [comment]
wait for issue 26.

**Comment by matteoghera** [comment]
The issue #26 is ready. You can merge and start to work!

**Comment by LorenzoEscriva** [comment]
i must wait the wrapper class to implement this class...
