### ISSUE TITLE
Refractor the code

### ISSUE THREAD

**Issue by matteoghera** [LorenzoEscriva/ProgettoFinale#29]
Refractor the code: add the MongoTestHelper class at the package com.tap.project.escrivaghera.AccountantApp.helper with the common code of class MongoDatabaseWrapperTest and AccountantAppIT

**Comment by LorenzoEscriva** [comment]
wait for the other issue.

**Comment by LorenzoEscriva** [comment]
Matte, the new branch doesn't work. The class MongoDatabaseWrapperTest doesn't work, now i go to lunch, i will rework that class in the afternoon. If you want, look the problems.

**Comment by matteoghera** [comment]
Add the class GenericHelperClass with method:
createDate, class AccountantAppTest, AccountantAppIT, MongoDatabaseWrapper
create TestList, class AccountantAppTest, Journal EntryTest, AccountantAppIT, MongoDatabaseWrapperTest

The MongoTestHelper class extends this class with methods:
constructor with MongoClient instance
addRecord AccountantAppIT MongoDatabaseWrapper
