### ISSUE TITLE
Add class AccountantApp

### ISSUE THREAD

**Issue by matteoghera** [LorenzoEscriva/ProgettoFinale#8]
Add the main class with this fields:
Session mySession
Database myDb
Server myServer

Furthermore add class constructor with Server instance, add the method authenticate(User anUser) that interacts with server for take a Session.

Add the method add(JounalEntry newEntry), modify(String id, JounalEntry changeEntry), delete(String id) and getAllRegistration(Date, Date ). All method must interact with method of Database and Session classes.
Add the method createJournalEntry(String id, Date date, List<Count> counts) that create a new JornalEntry object.

**Comment by matteoghera** [comment]
Attention: The class AccountantApp's method can run only when the authenticate method is been run one time

**Comment by LorenzoEscriva** [comment]
I will start that issue in the afternoon ;)
